// anychart-front/ChartRenderer.vue
<template>
  <div ref="chartEl" class="chart-container"></div>
</template>

<script setup>
import {onBeforeUnmount, onMounted, ref, watch} from 'vue';
import * as echarts from 'echarts/core';
import {BarChart} from 'echarts/charts';
import {GridComponent, LegendComponent, TitleComponent, TooltipComponent} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';

echarts.use([BarChart, GridComponent, TooltipComponent, TitleComponent, LegendComponent, CanvasRenderer]);

const props = defineProps({
  chartId: {type: String, required: true},
  variables: {type: Object, default: () => ({})},
  graphqlUrl: {type: String, default: '/graphql'},
  pollInterval: {type: Number, default: 0} // 0 不轮询，示例用轮询替代 subscription
});

const chartEl = ref(null);
let chartInstance = null;
let pollHandle = null;

async function fetchRenderedOption(chartId, variables, graphqlUrl) {
  const q = `
    query Render($id: ID!, $vars: JSON) {
      renderChart(id: $id, variables: $vars) {
        id
        option
      }
    }`;
  const resp = await fetch(graphqlUrl, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({query: q, variables: {id: chartId, vars: variables}})
  });
  const json = await resp.json();
  return json.data?.renderChart?.option || null;
}

onMounted(async () => {
  chartInstance = echarts.init(chartEl.value);
  const load = async () => {
    try {
      const option = await fetchRenderedOption(props.chartId, props.variables, props.graphqlUrl);
      if (option) {
        chartInstance.setOption(option, true);
      }
    } catch (e) {
      console.error('render error', e);
    }
  };
  await load();
  if (props.pollInterval > 0) {
    pollHandle = setInterval(load, props.pollInterval);
  }
});

onBeforeUnmount(() => {
  if (chartInstance) chartInstance.dispose();
  if (pollHandle) clearInterval(pollHandle);
});

// 当 variables 变更时刷新
watch(() => props.variables, async () => {
  if (!chartInstance) return;
  const option = await fetchRenderedOption(props.chartId, props.variables, props.graphqlUrl);
  if (option) chartInstance.setOption(option, true);
}, {deep: true});
</script>

<style>
.chart-container {
  width: 100%;
  height: 400px;
}
</style>

// anychart-front/src/components/ChartRenderer.jsx
import React, {useEffect, useRef, useState} from 'react';
import * as echarts from 'echarts';

function ChartRenderer({chartId, variables = {}, graphqlUrl = '/graphql', pollInterval = 0}) {
    const chartRef = useRef(null);
    const chartInstanceRef = useRef(null);
    const pollHandleRef = useRef(null);

    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    async function loadChart() {
        setLoading(true);
        setError(null);
        try {
            const resp = await fetch(graphqlUrl, {
                method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({
                    query: `query Render($id: ID!, $vars: JSON) {
            renderChart(id: $id, variables: $vars) { id option }
          }`, variables: {id: chartId, vars: variables}
                })
            });
            if (!resp.ok) throw new Error('Network error: ' + resp.status);
            const json = await resp.json();
            if (json.errors) throw new Error(JSON.stringify(json.errors));

            const renderResult = json.data?.renderChart;
            const chartOption = renderResult?.option?.option || renderResult?.option;

            if (chartOption && chartInstanceRef.current) {
                chartInstanceRef.current.setOption(chartOption, true);
            }
        } catch (e) {
            console.error(e);
            setError(e.message || String(e));
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        // 初始化 ECharts
        if (chartRef.current && !chartInstanceRef.current) {
            chartInstanceRef.current = echarts.init(chartRef.current);

            const handleResize = () => {
                if (chartInstanceRef.current) {
                    chartInstanceRef.current.resize();
                }
            };
            window.addEventListener('resize', handleResize);

            return () => {
                window.removeEventListener('resize', handleResize);
                if (chartInstanceRef.current) {
                    chartInstanceRef.current.dispose();
                    chartInstanceRef.current = null;
                }
            };
        }
    }, []);

    useEffect(() => {
        loadChart();

        // 设置轮询
        if (pollInterval > 0) {
            pollHandleRef.current = setInterval(loadChart, pollInterval);
        }

        return () => {
            if (pollHandleRef.current) {
                clearInterval(pollHandleRef.current);
                pollHandleRef.current = null;
            }
        };
    }, [chartId, variables, graphqlUrl, pollInterval]);

    return (<div>
            {loading && <div className="loading">加载中...</div>}
            <div ref={chartRef} className="chart-container"></div>
            {error && <div className="error">错误：{error}</div>}
        </div>);
}

export default ChartRenderer;
